### ISSUE TITLE
Wired.com sponsored stories 

### ISSUE THREAD

**Issue by mldangelo** [typpo/ad-detector#30]
See: http://www.wired.com/2015/07/strange-clothes-came-regular-old-3-d-printer/

**Comment by jdalton** [comment]
Is there a way to detect it on Wired?

**Comment by mldangelo** [comment]
When I posted that article in July it said it was sponsored. I'm a little surprised that it no longer says so.  Check out: http://www.wired.com/insights/2015/03/10-ways-worlds-first-open-server-architecture-disruptive/  for an example of other sponsored content.
