### ISSUE TITLE
[request] NRC Q

### ISSUE THREAD

**Issue by joepie91** [typpo/ad-detector#34]
* __Example URL:__ http://www.nrcq.nl/advertorial/vergeet-wie-ik-ben-dat-moet-van-de-nieuwe-privacywet
* __Detection:__ URL path starts with `/advertorial/`

**Comment by Zegnat** [comment]
I can put in a pull request for this when I get home. `/advertorial/` seems to be a popular path addition in the Netherlands. Basically, just copy [these `adformatie.nl` rules](https://github.com/typpo/ad-detector/blob/master/src/rules.js#L34-L41) and match them against `nrcq.nl`:

```
  'nrcq.nl': [
    {
      example: 'http://www.nrcq.nl/advertorial/vergeet-wie-ik-ben-dat-moet-van-de-nieuwe-privacywet',
      match: function() {
        return urlContains('/advertorial/');
      },
    },
  ],
```

**Comment by typpo** [comment]
PR #35 should solve this issue.  Thank you for the help!

Note that this won't go out til the extension itself is updated, which will happen soon(ish).
