### ISSUE TITLE
TheNextWeb support

### ISSUE THREAD

**Issue by joepie91** [typpo/ad-detector#36]
Example URL: http://thenextweb.com/insider/2016/01/26/designing-for-a-better-tomorrow/

**Comment by joepie91** [comment]
Another particularly well-disguisted example case: http://thenextweb.com/dd/2016/01/07/windows-10-frees-single-ecosystem/

**Comment by typpo** [comment]
Thanks for the report!  Sorry it took so long to get to.  The rule will go out in the next push (sometime soon).

**Comment by joepie91** [comment]
No worries, thanks :)
