### ISSUE TITLE
[request] Several Dutch sites

### ISSUE THREAD

**Issue by joepie91** [typpo/ad-detector#42]
Examples:

* https://www.bright.nl/sponsored-special/bright-lezers-geven-de-meedenkende-klantenservice-van-xs4all-een-84
* http://www.iculture.nl/promo/eindoordeel-xs4all-iculture-insiders/
* http://androidworld.nl/business/xs4all-klantenservice-getest-het-eindoordeel-en-kantoorbezoek/

It seems the first two can be determined based on the URL (`sponsored-special`/`promo`), but the third one can't be - there's an "Advertorial" badge on the page, though.

**Comment by typpo** [comment]
Added the first two.  Keeping this open for the last one.  Thanks Sven!

**Comment by Zegnat** [comment]
Can't commit anything right now, but for `androidworld.nl` this seems to do the trick:

```js
  'androidworld.nl': [
    {
      example: 'http://androidworld.nl/business/xs4all-klantenservice-getest-het-eindoordeel-en-kantoorbezoek/',
      match: function() {
        return selectorContains('.card-content__meta a', 'Advertorial');
      }
    }
  ],
```

**Comment by typpo** [comment]
Thank you Martijn!
