### ISSUE TITLE
[request] Motherboard/VICE

### ISSUE THREAD

**Issue by joepie91** [typpo/ad-detector#43]
__Example URL:__ https://motherboard.vice.com/read/the-swedish-fish-theory

Not sure how to detect this one, as it appears to be a manually added image. I don't know whether they have any other sponsored items, either.

**Comment by ndarville** [comment]
Three options:

1)
```html
<meta name="keywords" content="Swedish Fish Theory, SFT, sponsored" />
<meta name="news_keywords" content="Swedish Fish Theory, SFT, sponsored" />
```

2)
```html
<div class="ad-sponsored-by">
    <div class="motherboard-ad ad-banner" data-ref="sponsored_content_top"></div>					</div>
```

3)
```html
<span class="tags"><span class="tag"><a href="/tag/sponsored">sponsored</a></span></span>
```

**Comment by typpo** [comment]
Added a rule `classAppears('ad-sponsored-by')` for motherboard.  Thanks to both of you!
